#!/usr/bin/env python3

# USER CONFIGURATION

OUTFILE_NAME = 'make_cuts.sh'
CRF = "16"
PRESET = "superfast"

# END USER CONFIGURATION

import sys
import subprocess
from pathlib import Path

if len(sys.argv) <= 1:
    sys.exit()

INFILE_NAME = sys.argv[-1]

if not Path(INFILE_NAME).is_file():
    print("Invalid infile:", INFILE_NAME)
    sys.exit()

print("Using:", INFILE_NAME)


def line_is_valid(line):
    if line.strip():
        return True
    return False

if "-o" not in sys.argv:
    with open(INFILE_NAME, 'r') as infile:
        for line in infile:

            if not line_is_valid(line):
                continue

            split_line = line.split(":", 1)
            infile_name = split_line.pop(0)
            infile_name_noext = infile_name.split(".")[0]

            times = split_line[0].split()
            start_time = times[0]
            end_time = times[1]
            start_time_dashed = start_time.replace(":", "-")
            end_time_dashed = end_time.replace(":", "-")

            subprocess.run([
                "ffmpeg",
                "-ss", start_time,
                "-i", infile_name,
                "-t", str(float(end_time) - float(start_time)),
                "-crf", CRF,
                "-preset", PRESET,
                "-pix_fmt", "yuv420p",
                f"CUTS/CUT_{infile_name_noext}_FROM_{start_time_dashed}_TO_{end_time_dashed}.mp4"
            ])

else:

    out_string = "mkdir CUTS/\n"

    with open(INFILE_NAME, 'r') as infile:
        for line in infile:

            if not line_is_valid(line):
                continue

            split_line = line.split(":", 1)
            infile_name = split_line.pop(0)
            infile_name_noext = infile_name.split(".")[0]

            times = split_line[0].split()
            start_time = times[0]
            end_time = times[1]
            start_time_dashed = start_time.replace(":", "-")
            end_time_dashed = end_time.replace(":", "-")

            out_string += f"ffmpeg -ss {start_time} -to {end_time} -i \"{infile_name}\""
            out_string += f" -crf {CRF} -preset {PRESET} -pix_fmt yuv420p "
            out_string += f"\"CUTS/CUT_{infile_name_noext}_FROM_{start_time_dashed}_TO_{end_time_dashed}.mp4\""
            out_string += "\n"

    with open(OUTFILE_NAME, 'w') as outfile:
        outfile.write(out_string.strip("\n"))
    print("Done.")
