#!/usr/bin/env python3

## START USER CONFIG

RADIUS = 10

## END USER CONFIG

import sys
import subprocess
from pathlib import Path

if len(sys.argv) <= 1:
	print("No file chosen, exiting.")
	sys.exit()

infile_name = sys.argv[-1]

if not Path(infile_name).is_file():
	print("Invalid infile:", infile_name)
	sys.exit()

print("Using:", infile_name)

def line_is_valid(line):
	if line.strip():
		return True
	return False

ims = []

with open(infile_name, 'r') as infile:
	for line in infile.readlines():
		if not line_is_valid(line):
			continue
		ims.append(float(line.split(":")[1].strip()))

if len(ims) <= 0:
	sys.exit()

ims.sort(key=float)

def get_range(im):
	return [(im - RADIUS > 0) and (im - RADIUS) or 0, im + RADIUS]

ranges = [get_range(ims.pop(0))]

for im in ims:

	if im - ranges[-1][1] > RADIUS:
		ranges.append(get_range(im))

	else:
		ranges[-1][1] = im + RADIUS

movie_filename = Path(infile_name).stem

out_string = ""
for cut in ranges:
	out_string += movie_filename + ": " + str(cut[0]) + " " + str(cut[1]) + "\n"

print(out_string)


cut_list_filename = Path(movie_filename).stem
with open(cut_list_filename + ".txt", "w") as infile:
	infile.write(out_string)
